### ISSUE TITLE
Problem with ipware version

### ISSUE THREAD

**Issue by Arussil** [fabiocaccamo/django-maintenance-mode#84]
**Python version**
3.8.5

**Django version**
2.2.24

**Package version**
0.16.1

**Current behavior (bug description)**
Setting MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS = 'ipware.ip.get_ip' as stated in the documentation result in a 500 error: settings.MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS is not a valid function path. if ipware version is > 2.1

**Expected behavior**
Documentation should specify lower version of ipware is to be used for it to work.

From version 3 onward (https://github.com/un33k/django-ipware/blob/3.0.0/ipware/ip.py) there's been a refactor that changed name and returned params of that method.

**Comment by fabiocaccamo** [comment]
@Arussil the purpose of the example in the documentation is to show that it is possible define a custom function path for the `MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS`.

I see now that the latest `ipware` version return a tuple, you can simply create your own adapter and config `MAINTENANCE_MODE_GET_CLIENT_IP_ADDRESS` to point to it instead of directly to the `ipware` module.

I hope to have been helpful.
